name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig fmt --check .
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build test